import { createApp } from 'vue'
import './assets/styles/main.scss'
import App from './App.vue'
import router from "./routes/index";

const app = createApp(App);
const options = {
  city: [
    { title: "Dubai" },
    { title: "Abu Dhabi" },
    { title: "Sharjah" },
    { title: "Ajman" },
    { title: "Umm Al Quwain" },
    { title: "Ras Al Khaimah" },
    { title: "Fujairah" },
  ],
  developer: [
    { title: "Aqua Properties" },
    { title: "S&S Developments" },
    { title: "AAF Developments" },
    { title: "Aark Developers" },
    { title: "ABA Group" },
    { title: "AG Properties" },
    { title: "Al Habtoor Properties" },
    { title: "Al Marina" },
    { title: "Aldar Properties" },
    { title: "Alta Real Estate Development" },
    { title: "Amwaj Development" },
    { title: "ANAX Developments" },
    { title: "Aqasa Developers" },
    { title: "Arabian Gulf Properties" },
    { title: "Axiom Prime Real Estate" },
    { title: "AYS Developers" },
    { title: "Azizi Developments" },
    { title: "Baraka Real Estate Development" },
    { title: "Beyond Developments" },
    { title: "Binayah Properties" },
    { title: "Binghatti Developers" },
    { title: "Blanco Thornton" },
    { title: "Citi Developers" },
    { title: "Condor Developers" },
    { title: "Condor Group" },
    { title: "DAMAC" },
    { title: "Danube Properties" },
    { title: "Deyaar" },
    { title: "Dugasta Properties" },
    { title: "Durar Development" },
    { title: "Eagle Hills" },
    { title: "Ellington Properties" },
    { title: "Emaar Properties" },
    { title: "Empire Development" },
    { title: "Enso Development" },
    { title: "Esnad Management" },
    { title: "Fakhruddin Properties" },
    { title: "Gj Real Estate" },
    { title: "Golden Wood" },
    { title: "Green Group" },
    { title: "HMB Homes Real Estate Development" },
    { title: "HRE Development" },
    { title: "Iman Developers" },
    { title: "Invest Group Overseas (IGO)" },
    { title: "JVC Properties Dubai" },
    { title: "Laya Developers (Akshara Global)" },
    { title: "Leos Developments" },
    { title: "LIV Developers" },
    { title: "London Gate" },
    { title: "Lucky Aeon" },
    { title: "Madain Properties" },
    { title: "Majid Al Futtaim" },
    { title: "Majid Developments" },
    { title: "MAK Developers" },
    { title: "Meraas" },
    { title: "Meraki Developers" },
    { title: "Mered Group" },
    { title: "Metac Properties" },
    { title: "MGS Development" },
    { title: "Mr. Eight Development" },
    { title: "NABNI" },
    { title: "Nakheel" },
    { title: "Nshama" },
    { title: "Object 1 Development" },
    { title: "Object One Real Estate Development" },
    { title: "Omniyat" },
    { title: "ORO24" },
    { title: "Pantheon Development" },
    { title: "Park Group" },
    { title: "Premier Choice" },
    { title: "Prescott Development" },
    { title: "Prestige One Developments" },
    { title: "Pure Gold Real Estate Developers" },
    { title: "Qube Development" },
    { title: "Reef Luxury Development" },
    { title: "Reportage Properties" },
    { title: "Rijas Aces Property" },
    { title: "Riviera Group" },
    { title: "Royal Development" },
    { title: "Samana Developers" },
    { title: "Segrex Development" },
    { title: "Signature Developers" },
    { title: "Sobha Realty" },
    { title: "STAMN Real Estate Development" },
    { title: "Summit Real Estate Development" },
    { title: "Svarn Development" },
    { title: "Tabeer Development" },
    { title: "Taraf Holding" },
    { title: "Tiger Properties" },
    { title: "Tiger Properties Double" },
    { title: "Town X Real Estate Development" },
    { title: "Tuscany" },
    { title: "Union Properties" },
    { title: "Valores Property Development LLC" },
    { title: "Vantage Properties" },
    { title: "Vincitore Real Estate Development LLC" },
    { title: "Wasl Properties" },
  ],
  region: [
    { title: "Al Barari" },
    { title: "Al Barsha 1" },
    { title: "Al Barsha 2" },
    { title: "Al Barsha 3" },
    { title: "Al Furjan" },
    { title: "Al Habtoor City" },
    { title: "Al Jaddaf" },
    { title: "Al Khail Heights" },
    { title: "Al Reem Island, Abu Dhabi" },
    { title: "Al Sufouh 1" },
    { title: "Al Sufouh 2" },
    { title: "Al Wasl (City Walk)" },
    { title: "Arabian Ranches" },
    { title: "Arabian Ranches 2" },
    { title: "Arabian Ranches 3" },
    { title: "Arjan" },
    { title: "Barsha South" },
    { title: "Bluewaters Island" },
    { title: "Business Bay" },
    { title: "Cherrywoods" },
    { title: "City of Arabia" },
    { title: "Complex (Dubailand)" },
    { title: "Creekside" },
    { title: "Culture Village" },
    { title: "Damac Hills" },
    { title: "Damac Hills 2" },
    { title: "Damac Lagoons" },
    { title: "Discovery Gardens" },
    { title: "Downtown Dubai" },
    { title: "Dubai Creek Harbour" },
    { title: "Dubai Design District" },
    { title: "Dubai Festival City" },
    { title: "Dubai Golf City" },
    { title: "Dubai Harbour" },
    { title: "Dubai Healthcare City" },
    { title: "Dubai Hills" },
    { title: "Dubai International" },
    { title: "Dubai Investment Park" },
    { title: "Dubai Islands" },
    { title: "Dubai Marina" },
    { title: "Jumeirah Lake Towers (JLT)" },
    { title: "Jumeirah Park" },
    { title: "Jumeirah Village Circle (JVC)" },
    { title: "Jumeirah Village Triangle (JVT)" },
    { title: "La Mer" },
    { title: "Liwan" },
    { title: "Madina Jumeirah Living" },
    { title: "Mesk District" },
    { title: "Mina Al Arab, Ras Al Khaimah" },
    { title: "Mina Rashid" },
    { title: "Mirdif Hills" },
    { title: "Mirdif Tulip" },
    { title: "Mohammed Bin Rashid City (MBR)" },
    { title: "Motor City" },
    { title: "Mudon" },
    { title: "Nad Al Sheba" },
    { title: "Nshama" },
    { title: "Old Town" },
    { title: "Park Gate Residences" },
    { title: "Palm Jumeirah" },
    { title: "Ras Al Khor" },
    { title: "Remraam" },
    { title: "Rashid Yachts and Marina" },
    { title: "Sharjah" },
    { title: "Sheikh Zayed Road" },
    { title: "The Greens" },
    { title: "The Lakes" },
    { title: "The Meadows" },
    { title: "The Springs" },
    { title: "The Sustainable City" },
    { title: "The Valley" },
    { title: "The Villa" },
    { title: "The World Islands" },
    { title: "Tilal Al Ghaf" },
    { title: "Town Square" },
    { title: "Villanova" },
    { title: "Wadi Al Safa 5" },
    { title: "YAS Island" },
  ],
  type: [
    { title: "Apartment" },
    { title: "Villa" },
    { title: "Townhouse" },
    { title: "Penthouse" },
    { title: "Duplex" },
    { title: "Studio" },
    { title: "Commercial Property" },
    { title: "Office" },
    { title: "Retail" },
    { title: "Land" },
    { title: "Hotel" },
    { title: "Serviced Apartment" },
  ],
  furnishing: [{ title: "Furnished" }, { title: "Unfurnished" }],
  status: [{ title: "AVAILABLE" }, { title: "RENTED" }],
  postdelivery: [{ title: "YES" }, { title: "NO" }],
  readiness: [{ title: "READY" }, { title: "UNDER CONSTRUCTION" }, { title: "SHORT TERM RENTAL" }],
};

app.provide('options',options)
app.use(router)
app.mount('#app')
